import { Params } from "./types";

export const stableDefaultParams: Params = {
  waterDepthScale: 0.08,
  noCornerCutting: false,
  springOutput: {
    spring: 3,
    summer: 2.4,
    autumn: 1.2,
    winter: 0,
  },
  waterReserve: 0.02,
  maxOutflowRatio: 0.75,
  flatEpsilon: 0.035,
  flatDiffusionRatio: 0.28,
  evaporationRate: {
    spring: 0.002,
    summer: 0.004,
    autumn: 0.002,
    winter: 0.001,
  },
  seepageRate: 0.0015,
  seepToMoistureRatio: 0.72,
  moistureEvaporationRate: 0.002,
  oceanMoistureBaseline: 1,
  wetMoistureThreshold: 0.08,
  wetWaterThreshold: 0.04,
  flowMemoryDecay: 0.92,
  standingWaterDecay: 0.96,
  riverThreshold: 1.8,
  riverFormTicks: 3,
  riverDecayThreshold: 0.35,
  riverDryTicks: 18,
  lakeMemoryThreshold: 2.5,
  lakeOutflowRatioThreshold: 0.9,
  lakeFormTicks: 3,
  lakeMinWater: 0.25,
  lakeDryTicks: 16,
  lakeAreaSoftCap: 80,
  lakeAreaPenalty: 1.35,
  lakeSpillEpsilon: 0.08,
  lakeSpillRate: 0.45,
  lakeSpillMax: 1.4,
};
